version: '3'
services:
    dolores:
        image: dolores:latest
        ports: 
          - '${FORWARD_DOLORES_PORT:-5000}:5000'
        environment:
             DATABASE_URL: 'mysql+pymysql://root:123456@mysql/dolores'
             APP_SETTINGS: 'config.StagingConfig'
             SECRET_KEY: 'b822c3cc-ebde-4347-acd9-cce2967108de'
             SUPER_ADMIN_USERNAME: 'michael123'
             GRPC_PREDICTOR_MANAGER_NODE: 'prediction_manager:50051'
        networks:
            - microservices
        depends_on:
            - mysql

    prediction_manager:
        image: prediction_manager:latest
        ports: 
          - '${FORWARD_PREDICTION_MANAGER_PORT:-50051}:50051'
        environment:
             GRPC_SERVER_PORT: '50051'
             GRPC_THREAD_POOL_EXECUTOR_MAX_WORKERS: '10'
        networks:
            - microservices
        depends_on:
            - mysql

    mysql:
        image: mysql
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_INITDB_SKIP_TZINFO: '1'
        volumes:
            - 'microservices_mysql:/var/lib/mysql'
        networks:
            - microservices
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p123456"]
          retries: 3
          timeout: 5s

    adminer:
      image: adminer
      ports:
        - '${FORWARD_ADMINER_PORT:-28080}:8080'
      networks:
        - microservices
      depends_on:
        - mysql


networks:
  microservices:
      driver: bridge

volumes:
    microservices_mysql:
        driver: local
